export const mockActivityData2 = [
  {
    achievement_count: 43,
    athlete: { id: 28437315, resource_state: 1 },
    athlete_count: 2,
    average_heartrate: 132.8,
    average_speed: 7.537,
    average_watts: 0,
    comment_count: 0,
    commute: false,
    device_watts: false,
    display_hide_heartrate_option: true,
    distance: 54502.4,
    elapsed_time: 7905,
    elev_high: 93,
    elev_low: -5.8,
    end_latlng: [49.261999, -123.20742],
    external_id: "469401899750162452.fit",
    flagged: false,
    from_accepted_tag: false,
    gear_id: "b12439766",
    has_heartrate: true,
    has_kudoed: false,
    heartrate_opt_out: false,
    id: 14646885957,
    kilojoules: 0,
    kudos_count: 15,
    location_city: null,
    location_country: null,
    location_state: null,
    manual: false,
    map: {
      id: "a14646885957",
      resource_state: 2,
      summary_polyline:
        "sntkH|t_oVI|X`@PtPPfAj@Zz@FbIQpm@\\~L~@~J`ClNbEdN`BzGZhE|@vArBtIAZ|BpHFjDtAzCpHhYbAlAr@?\\Yl[mr@`IuSrO}\\lCaH`CwHrDyO~B{O`A}KlEur@dAcKrAyInQ{bAz[omAPuDDsZPuBjPal@`IgR^mBb@mFf@_CzD}IzEoFf@cAnAwENiH~@wCn@gArAi@tIH~CmAh}@{}@l@_BVuB@}UL}Ed@QhMLfAm@fC_Il@kD|FuUx@iBfAeArA_@~AJt]zJpBzAnBrChAbDn@jE]\\g@c@E_@VyAI{@q@qAyAqA?y@f@gCCg@oCeBeAUiA^}AbCaA`DaElVSxBArg@[XwCa@aBHaBp@oAjAgP~]u@jBc@|BkAnQ{UjjEAxI\\~Hz@`IdEvVFjCQfCi@`CoAnBuAx@kBNsMa@yKsB_LeDoAVuAjCoA~E_@hCVtc@MfG]|DyAvDmBvAoAJqDu@pDr@~AQbByAt@{A\\uAb@wEFuGW_b@ToBjA}Eh@{Av@iApA_@xLtD|HxAtEb@xHFdBK|Ay@nAeBv@kCTiCImDgEkWu@kHYqH?}HtTy_Eb@cLdAmNh@uCdQk`@hAqAdAm@zAY|AD~KpBzLvGxCb@rKgAbKIv@i@d\\@rAYtBDpD]dALbBi@pA?jAr@pMtQXr@StCXpAtGrDt@t@l@`BThCzAx_AAhJ[nHgApLu@lB{Ar@Q\\YlFf@fRiAfHe@fHg@dBf@aBh@_IdAeGe@qRXsFfB_A|@gB`AmK\\uGBoM{AebAc@sB{@yAsGwEIeA^mAM_@q@YeNiRiAy@eAG{Br@qAQyC`@yERy`@MqCXeD_@u@\\kIp@yEaA_IqEkHaBKe@G{KFuZnDuV`A{Dp@_BfBuBhBLtEpChBnCrGfEf@x@l@dCKZaA@qC{@uA`@oA_GaAkCkCmDgCgBkQkFcKaEwAMqA\\_Az@m@jAeIxZ[`Aw@dA\\tAAv@oAtDqAt@eMU{@PC~\\SpBi@xAc}@x}@_DnA}IGwAp@q@nAy@pCQlHgAdE{@zAsEfF{DbJa@jBk@fGa@xBeI`ReP`l@OpBCx[[fDwWfbA_CvGgLtn@iFhZcBvMeFlw@}@lJeCbP_DxMyFlP{Od]uH~R_Px]cJjQgA^m@UYa@eFeSiAoCMcCu@oB{FmUMaCq@sAqGuVqCaP}@kK]yKNmm@QeMc@YuTg@@oW",
    },
    max_heartrate: 154,
    max_speed: 12.7,
    moving_time: 7231,
    name: "Afternoon Ride",
    photo_count: 0,
    pr_count: 17,
    private: false,
    resource_state: 2,
    sport_type: "Ride",
    start_date: "2025-05-31T00:13:12Z",
    start_date_local: "2025-05-30T17:13:12Z",
    start_latlng: [49.261983, -123.208246],
    suffer_score: 50,
    timezone: "(GMT-08:00) America/Vancouver",
    total_elevation_gain: 291,
    total_photo_count: 0,
    trainer: false,
    type: "Ride",
    upload_id: 15629644529,
    upload_id_str: "15629644529",
    utc_offset: -25200,
    visibility: "everyone",
    workout_type: 10,
  },
  {
    achievement_count: 22,
    athlete: { id: 28437315, resource_state: 1 },
    athlete_count: 2,
    average_cadence: 87.2,
    average_heartrate: 157.8,
    average_speed: 3.216,
    average_watts: 237.9,
    comment_count: 0,
    commute: false,
    device_watts: true,
    display_hide_heartrate_option: true,
    distance: 13669.3,
    elapsed_time: 4287,
    elev_high: 89,
    elev_low: 65,
    end_latlng: [49.262025, -123.206309],
    external_id: "469379008646119438.fit",
    flagged: false,
    from_accepted_tag: false,
    gear_id: null,
    has_heartrate: true,
    has_kudoed: false,
    heartrate_opt_out: false,
    id: 14637290470,
    kilojoules: 1011.2,
    kudos_count: 24,
    location_city: null,
    location_country: null,
    location_state: null,
    manual: false,
    map: {
      id: "a14637290470",
      resource_state: 2,
      summary_polyline:
        "yatkHdh_oVhA?t@FTD\\VH@fB?H@BH?p@Dx@G`@AT@nAK`QC`LCbAEJSPALHr@@d@O~IFjIGbD?bDKhAFlAA`KBnHPfHVfDr@tFx@bFJbAnA~F`B`Hv@vCNZb@NHHHLL^`@nBTrA@d@MhA@TVf@j@`@PX~CrMnA`FDd@Ef@Kr@@NNr@FHTHTTP\\HXFZ@TCr@BJ`@x@fA|Dz@bE\\hBh@bB^|AHn@?rAARMb@cArBSXsBvBu@l@c@XGJCr@GJi@h@g@r@IFSFSPa@h@cAhAq@`Aw@v@iAxAy@rB[hAGv@Hh@ANKd@_@fA]l@SXc@^e@RiA\\kAXcCp@q@Xc@Xw@`A[l@]lAgApEWr@U\\WVYPeAZ[LKHS\\Yr@S\\WZe@VYFM?sA_@YAa@J_@VUXS`@oBpFe@~@WT[Ni@BmCm@kAUg@CmBAqAO_@KsAc@}@i@oB{Ao@m@IMSc@O{@s@qAUi@yAmEo@yAk@cA_AaCY{@_B_E_BwCoAuC_ByEYiA]kAeA_GM{@Ke@CU@UPq@?MU]Qe@GQIaAOkDOkHGqF@eCFmIHyCJmBHoCVwEJaBX}BDwAn@eGVyBp@sEhB_KzAmGj@sBl@_CdAkD|DyK|AuDfB_FrAeDNk@Ho@Pi@~BuFvDwJh@}APSJCH@HBHHJXB\\@pCMxN?hEC|CCt@MfAK`AKj@q@hCORIBIAIGK[S{AO{AWgA_@qAMYk@eA}BcDMYAO@ODM\\q@|E_Mb@aAtA{DNUHCJ@PJNb@Bh@?rBKjQ?pCCfDOdBWpBw@rCGHI@KAKGM]U{BQmA[oAa@kAg@cAgCiDK[?OLe@vFgNxCiI`@oCNuAFiAFeCBsFBqB@UDIRAbFJ\\A`A@^CrAF|C?`CF~@AjKNZATi@FERAn@Dr@?HCCcBBgGBw@?gAByAAiCDmFAiA?MJ_@IgADkDAs@FcCCgCBgAAq@CGAAs@ByBG",
    },
    max_heartrate: 186,
    max_speed: 4.6,
    max_watts: 334,
    moving_time: 4251,
    name: "Temple run",
    photo_count: 0,
    pr_count: 13,
    private: false,
    resource_state: 2,
    sport_type: "Run",
    start_date: "2025-05-30T01:32:28Z",
    start_date_local: "2025-05-29T18:32:28Z",
    start_latlng: [49.262044, -123.207777],
    suffer_score: 113,
    timezone: "(GMT-08:00) America/Vancouver",
    total_elevation_gain: 90,
    total_photo_count: 0,
    trainer: false,
    type: "Run",
    upload_id: 15619283817,
    upload_id_str: "15619283817",
    utc_offset: -25200,
    visibility: "everyone",
    weighted_average_watts: 244,
    workout_type: 0,
  },
  {
    achievement_count: 0,
    athlete: { id: 28437315, resource_state: 1 },
    athlete_count: 1,
    average_cadence: 27.2,
    average_heartrate: 130.9,
    average_speed: 0.847,
    average_temp: 27,
    comment_count: 0,
    commute: false,
    display_hide_heartrate_option: true,
    distance: 2300,
    elapsed_time: 3446,
    elev_high: 0,
    elev_low: 0,
    end_latlng: [],
    external_id: "469354391772626952.fit",
    flagged: false,
    from_accepted_tag: false,
    gear_id: null,
    has_heartrate: true,
    has_kudoed: false,
    heartrate_opt_out: false,
    id: 14626410060,
    kudos_count: 16,
    location_city: null,
    location_country: null,
    location_state: null,
    manual: false,
    map: { id: "a14626410060", resource_state: 2, summary_polyline: "" },
    max_heartrate: 157,
    max_speed: 0.94,
    moving_time: 2715,
    name: "Afternoon Swim",
    photo_count: 0,
    pr_count: 0,
    private: false,
    resource_state: 2,
    sport_type: "Swim",
    start_date: "2025-05-29T00:18:27Z",
    start_date_local: "2025-05-28T17:18:27Z",
    start_latlng: [],
    suffer_score: 43,
    timezone: "(GMT-07:00) America/Creston",
    total_elevation_gain: 0,
    total_photo_count: 0,
    trainer: true,
    type: "Swim",
    upload_id: 15607604338,
    upload_id_str: "15607604338",
    utc_offset: -25200,
    visibility: "everyone",
  },
  {
    achievement_count: 3,
    athlete: { id: 28437315, resource_state: 1 },
    athlete_count: 1,
    average_cadence: 85.6,
    average_heartrate: 149.1,
    average_speed: 2.751,
    average_watts: 204.6,
    comment_count: 0,
    commute: false,
    device_watts: true,
    display_hide_heartrate_option: true,
    distance: 10320,
    elapsed_time: 3756,
    elev_high: 92,
    elev_low: 73,
    end_latlng: [49.262054, -123.207222],
    external_id: "469345560516657173.fit",
    flagged: false,
    from_accepted_tag: false,
    gear_id: null,
    has_heartrate: true,
    has_kudoed: false,
    heartrate_opt_out: false,
    id: 14622005242,
    kilojoules: 767.6,
    kudos_count: 27,
    location_city: null,
    location_country: null,
    location_state: null,
    manual: false,
    map: {
      id: "a14622005242",
      resource_state: 2,
      summary_polyline:
        "cotkH~t_oVKbW?NDFH@bAEf@LDb@FJHFH@b@C~@?`@Bv@AxFLRHl@f@Vb@HZD\\?h@MfHA~ADnIGvCBjBCt@It@APFx@@dDCxCBzJTxI\\lDh@`EVlAVbBX`CpBdJtBlILV^NRNRj@j@pCJp@@NAb@G^GJG?IIIMEQOqA_@}BiA_FmAwE{BaKO{@I_A]yBQ}@S_BKe@E@_@j@YZ_@N]Va@D}@j@G@[Ou@Ms@V[FGGCOE_DFuLBw@P{AFqBL}@R}BHk@B{@NsA^uCNaAvAcHp@yCl@iECEa@M_@]GA{@Ag@Wg@Ay@USB_@P]DSJI@QMQWS_AkAU]MGIIQScAAg@G_@@OXyA@w@Lc@BWBGH?^DVGZFXLD?LKFCH@PHRZDLHZJx@GZQb@CVBHTZBJ@NEl@@LJd@?NANGH]LS^MNEVClAUx@@jBPr@Hv@Bx@C\\Yp@YNCJ?\\CNELW`@?VBh@ANMTg@l@GXBXDRLXb@f@FV@ZALSl@CjADXRl@DZ@\\GVSh@APFd@@v@n@dBFn@@f@Rz@?\\GXY?_@TQF[DYAODAHDdBCVM^?JTf@TPBHCb@FTFFLHF?`@]H?DFBj@Lb@?j@BHLJPDlAEfA_@RBb@HZJF?HC\\_@ZMf@M`Ac@XYVe@LMVk@ZGHEFG@KQeBIiCSyCQiJ?qBHoB?y@?kAGaCBaEAeADmA@cHH}CA_E@sGIy@As@@cACsBByAAgABeAA_CBw@Hu@Gy@AqADyBAwJDm@@gB@sFD_C?}@Cs@DkC?oDHwC?{CB_@BOPQTIHDFJHZJTZPT?RENONYJa@BqEAsAG[S_@OKUCS?UJORKXEZCxFBr@HVRVXLLBRETQPYF[Be@@wFC[GQGQOOc@K[DWVOb@EZ@hBCjA?hA@ZFXHPPRZJR?PINOPa@Fk@B{ECs@G[S_@GGQE[ASFONMTGXG~ECJEHYPEHERClECDg@Cc@Bq@?e@Hs@?I@WVI@uBCM@CT@zA",
    },
    max_heartrate: 168,
    max_speed: 4,
    max_watts: 290,
    moving_time: 3752,
    name: "Morning Run",
    photo_count: 0,
    pr_count: 1,
    private: false,
    resource_state: 2,
    sport_type: "Run",
    start_date: "2025-05-28T15:04:33Z",
    start_date_local: "2025-05-28T08:04:33Z",
    start_latlng: [49.262079, -123.208904],
    suffer_score: 62,
    timezone: "(GMT-08:00) America/Vancouver",
    total_elevation_gain: 65,
    total_photo_count: 0,
    trainer: false,
    type: "Run",
    upload_id: 15602933111,
    upload_id_str: "15602933111",
    utc_offset: -25200,
    visibility: "everyone",
    weighted_average_watts: 206,
    workout_type: 0,
  },
  {
    achievement_count: 1,
    athlete: { id: 28437315, resource_state: 1 },
    athlete_count: 1,
    average_cadence: 86.2,
    average_heartrate: 157.2,
    average_speed: 3.199,
    average_watts: 231.8,
    comment_count: 2,
    commute: false,
    device_watts: true,
    display_hide_heartrate_option: true,
    distance: 13140.2,
    elapsed_time: 4729,
    elev_high: 88,
    elev_low: 86,
    end_latlng: [49.256433, -123.238983],
    external_id: "469333385089679368.fit",
    flagged: false,
    from_accepted_tag: false,
    gear_id: null,
    has_heartrate: true,
    has_kudoed: false,
    heartrate_opt_out: false,
    id: 14616869806,
    kilojoules: 952.2,
    kudos_count: 26,
    location_city: null,
    location_country: null,
    location_state: null,
    manual: false,
    map: {
      id: "a14616869806",
      resource_state: 2,
      summary_polyline:
        "}iskHdaeoVf@m@LeAWaAi@WmDdCSf@Ct@X`An@R`DcCVu@AaA]q@g@KcDdCYzAXbAp@R|C}BXs@@aAYu@i@OgDdCUj@A|@^|@j@JbDgCTw@C}@_@q@g@GcDdCUp@@|@\\t@j@JbDeCHOsBhBbBsAXy@KyA{@e@cDdCUl@At@X|@n@PdDgCTw@C_A[k@k@KcDdCSl@?z@^z@j@J~CeCVw@C{@]s@g@KeDfCSj@Az@Xx@l@NbDcCVo@?cA[q@i@OuCtBQPQf@C|@Xx@l@PbDaCVu@?_A]s@k@KcDdCU|ATz@n@VdDcCXw@Aw@[w@e@MgD`CYbAJnAv@b@rAy@rAiAVo@?}@Yw@g@OkDhCSh@At@X|@l@PdDcCTu@AeA[k@g@MeDdCWt@@t@^|@j@HbDiCR{@Cy@[m@g@KcDbCWn@Ax@Xx@n@PdDeCTu@C}@Yq@k@MgDhCQn@?v@Xv@l@N`DcCXw@Ay@Ys@o@O_DbCUj@Cx@Vz@p@R~C_CXu@?aA]u@c@KkDhCU|A\\bAn@L~CeCVw@C{@]s@e@KcDbCWp@Ax@\\z@l@L`DeCTs@?{@Yq@i@QeDbCWr@Av@Xv@n@PdDeCTw@EeA]k@g@G_D`CWl@Ax@Vx@t@R|CaCXy@A{@Yq@i@OgDdCYrAVfAn@V`D}BZw@?}@Uq@k@SgDbC[tATdAn@XfDcCVm@@y@Ok@_@_@o@H_DvCEdARt@h@Zh@SrCkCHgAW_AaAMqC|BWn@Az@Pn@^Vh@E`Aw@gAz@m@Ae@}@H}A~CoC~@HXx@GhAe@r@`@g@Lw@YhAsAhArAgARe@?qAc@w@u@B}CpCK`AP|@f@\\l@OnCaCPeAScA][g@B_DnCO`ALz@^`@j@A~CmCN_AOaAa@a@e@@aDnCO|@NdAd@`@h@IxCkCNcAUcAeAUcDzCGbARx@h@Zl@WpCiCDsAi@aAq@DmCvBWn@Av@Vx@d@Tf@OvCoCDuAg@}@s@BkCtBWl@Cv@Pv@^Xf@E~CqCJgAWaAaAO_DrCM~@RbAh@Zh@OvCoCDqAg@aAu@DkCtBWp@BnAd@p@j@?`Aw@",
    },
    max_heartrate: 185,
    max_speed: 6.5,
    max_watts: 389,
    moving_time: 4108,
    name: "Evening Run",
    photo_count: 0,
    pr_count: 1,
    private: false,
    resource_state: 2,
    sport_type: "Run",
    start_date: "2025-05-28T02:08:46Z",
    start_date_local: "2025-05-27T19:08:46Z",
    start_latlng: [49.256157, -123.238748],
    suffer_score: 106,
    timezone: "(GMT-08:00) America/Vancouver",
    total_elevation_gain: 0,
    total_photo_count: 0,
    trainer: false,
    type: "Run",
    upload_id: 15597377326,
    upload_id_str: "15597377326",
    utc_offset: -25200,
    visibility: "everyone",
    weighted_average_watts: 239,
    workout_type: 0,
  },
];
