export const mockActivityData = [
  {
    resource_state: 2,
    athlete: { id: 159770490, resource_state: 1 },
    name: "Belcarra Buntzen Ride",
    distance: 100221,
    moving_time: 16482,
    elapsed_time: 21713,
    total_elevation_gain: 1347,
    type: "Ride",
    sport_type: "Ride",
    workout_type: null,
    id: 14296715239,
    start_date: "2025-04-19T15:31:38Z",
    start_date_local: "2025-04-19T08:31:38Z",
    timezone: "(GMT-08:00) America/Vancouver",
    utc_offset: -25200,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 5,
    photo_count: 0,
    map: {
      id: "a14296715239",
      summary_polyline:
        "intkHda_oVe@xk@eTCKhAo@_BuRe@Jgv@vCuXoBkQNscAl@iA{V{@@gU`FceAW{UcEyNp@k@^qKx@emB[iC_Cu@eEaL_UycArRe^rB_MoGyb@dAoT}BwPx@q@}Ni\\?cZrBgGuEoBo@wJjAy~Bw@{BSkM|@wiIWc^oIq@O_Ad@ogFY_a@wEcAb@m|AsC_Ow`@{XyIaPwCoOZc\\oHoWoAiYLyItGun@tEcVz@wi@s@wWpGit@YyK}A{K}Mc\\qBaK_@yJtAwXMmPoE}]IuRzAiLvFmPbE}GdFeEhHiCrq@oD[ofBmKOzCQCkz@k@wEgF}FuAeFN_Ze\\vPoE~HcH`ZuKt[_K|f@{L|VeDpViTx\\}Df@eL~YeEjFeA|P{e@t@cFjFqCxKsMwBmCp@_BbFSfKz@l~@sBnAeMoAgJbOsLpMsHdB}BxD_BbQjBpRbExGbKfXrGpCbTvUrD~K~Gj\\f@pQiCzGuDbAiApKpI~CMeCnAwB|AbCzG^NiBwDkFw@qG|FqXJaGqDcOi@kJkGoRaB_DmGgEyAkHnAeP`CeG~@eLbBsDnDoCtFi_@q@uHsCqEuCNoDxCWtM_AYg@}JbCeQeAy~@d@gLmDaDg@aDlAsCjFoAhAkCFaDg@cHaAc@cCdBmAyBpAqNQ_PjA}FoLk@zEgP_Aub@gj@D}D_NeHeAqYlGcInGcDzJoBhBeD]yM{IyDxKyKaDmAlDuGtCzFoD`@}IpNzAhDcC~LpHbDVtC}BfCkI|GaGx]uHzBl@lE|M`Bz@`y@^h[hZvB`EKx]cEbFsBdFH|JeA`I^rFtBbBng@e@fA_QpEiGvKgY|D_A|Tc^jCkTrLmWhKeh@bLi]zFwWbDsGj^wRFpEfD_@dFpFElSoAtIZt~@aDbA`LP[vHNx{A{YVk_@dFoFnE{ElIgFzNeBvLGjRnFnc@FnM{ApZZlHjC`N`MdZbCpUqGbs@Xv\\s@ph@iFlVwFdk@c@zN`BbYnHnV@z^|D`PxEpJc@lLvDzRh`@`@mAh@@dErCb@pAgA_@d@`AVL~KfJTQpo@_MtQYrD^rE|C`@TnAYpiGvIj@NfB]xrJjAzDoAzgCb@hCjFvAvO{DpTvDg@bk@dS|h@bBrUrA`Fe@tu@wAfQgEbSyBvDgDpB_A|EUtKkEtBNpf@uCzA}AfoBq@r@zEdRAjVkF`gAGhOtj@pBEl]f@tCy@vMUb~@d`@fAGrc@eDKIsNvDk@ClPyO_@JgPtRHtAd@CpOkUM?gPjD]@yI",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: true,
    visibility: "only_me",
    flagged: false,
    gear_id: null,
    start_latlng: [49.26197, -123.208022],
    end_latlng: [49.26204, -123.207415],
    average_speed: 6.081,
    max_speed: 20.54,
    has_heartrate: true,
    average_heartrate: 137.5,
    max_heartrate: 177,
    heartrate_opt_out: false,
    display_hide_heartrate_option: true,
    elev_high: 183.4,
    elev_low: -11.2,
    upload_id: 15256139970,
    upload_id_str: "15256139970",
    external_id: "activity_18877198907.tcx",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 0,
    has_kudoed: false,
  },
  {
    resource_state: 2,
    athlete: { id: 159770490, resource_state: 1 },
    name: "Afternoon Run",
    distance: 5992.1,
    moving_time: 2252,
    elapsed_time: 4722,
    total_elevation_gain: 69.9,
    type: "Run",
    sport_type: "Run",
    workout_type: 0,
    id: 13701416944,
    start_date: "2025-02-23T01:28:06Z",
    start_date_local: "2025-02-22T17:28:06Z",
    timezone: "(GMT-08:00) America/Vancouver",
    utc_offset: -28800,
    location_city: null,
    location_state: null,
    location_country: null,
    achievement_count: 0,
    kudos_count: 0,
    comment_count: 0,
    athlete_count: 1,
    photo_count: 0,
    map: {
      id: "a13701416944",
      summary_polyline:
        "}ntkH~u~nVCCwAAs@Gc@?]EaBLM?CB}@@]CGEQk@o@By@Ag@D}ADIAEECQ?aCPiJ?{@BeA?gADgCBkCJeDAoCDsDEmJDuBCu@Dk@EiAEU?sAHmAf@}DQ[M_@Ms@EeA@w@Cq@Bm@@yCF}@@gAEaBDo@CsBHaBFaC?mDGw@PmDHcDCuADwEGaBFk@AyCGmBDi@Aw@FwGAoBJyBEc@Aq@@s@EIKAwCF]AWCu@BSCqADa@CcBBa@EkAAMOIs@?wDDgIQG?jCDTFB|BVj@JdBDj@CdBBp@Dz@C~@Bd@ADFDf@DdBCdEEx@@`E@v@C~@?tCEnABbB?xDC~@?rCIdLCxAEV?tCDz@ExABr@EX?rCGdE?dGI|C@jAAxADl@GZ?f@@b@Lj@b@l@YnASxAItB@|AG|ADvAM`UAbGC~EE~ABxDOnI@nAD\\Tb@JHjBDh@A^B`A?d@BfACnAFlAA",
      resource_state: 2,
    },
    trainer: false,
    commute: false,
    manual: false,
    private: true,
    visibility: "only_me",
    flagged: false,
    gear_id: null,
    start_latlng: [49.262072, -123.206231],
    end_latlng: [49.262833, -123.20621],
    average_speed: 2.661,
    max_speed: 3.937,
    average_cadence: 84.6,
    average_temp: 21,
    has_heartrate: false,
    heartrate_opt_out: false,
    display_hide_heartrate_option: false,
    elev_high: 85.5,
    elev_low: 15.9,
    upload_id: 14621622591,
    upload_id_str: "14621622591",
    external_id: "stripped_activity_18350484218.gpx",
    from_accepted_tag: false,
    pr_count: 0,
    total_photo_count: 1,
    has_kudoed: false,
  },
];
